CREATE TABLE IF NOT EXISTS cliente (
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  tipo_pessoa VARCHAR(15) NOT NULL,
  cpf_cnpj VARCHAR(20) UNIQUE,
  username VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(150) NOT NULL
);

ALTER TABLE venda DROP COLUMN IF EXISTS cliente_id;
ALTER TABLE venda ADD COLUMN IF NOT EXISTS cliente_id BIGINT;
ALTER TABLE venda ADD CONSTRAINT cliente_id_fk FOREIGN KEY(cliente_id) REFERENCES cliente(id);