ALTER TABLE usuario ADD COLUMN IF NOT EXISTS cpf VARCHAR(20) UNIQUE;

ALTER TABLE cliente ALTER COLUMN email SET NOT NULL;
ALTER TABLE cliente ALTER COLUMN tipo_pessoa DROP NOT NULL;
ALTER TABLE cliente ALTER COLUMN password DROP NOT NULL;
ALTER TABLE cliente ADD COLUMN IF NOT EXISTS ativado BOOL DEFAULT false;
