ALTER TABLE produto ADD COLUMN reserva INTEGER DEFAULT 0;

ALTER TABLE cliente ADD COLUMN created_at TIMESTAMP;
ALTER TABLE produto ADD COLUMN created_at TIMESTAMP;
ALTER TABLE usuario ADD COLUMN created_at TIMESTAMP;
ALTER TABLE fornecedor ADD COLUMN created_at TIMESTAMP;
ALTER TABLE tipo ADD COLUMN created_at TIMESTAMP;